=== AliSlth/CocoRebus/modeles/normes.DTD
<!ELEMENT TEI (teiHeader, text)>
	<!ELEMENT teiHeader (fileDesc, encodingDesc, profileDesc)>
		<!ELEMENT fileDesc (titleStmt, publicationStmt, sourceDesc)>
			<!ELEMENT titleStmt (title, respStmt+)>
				<!ELEMENT title (#PCDATA)>
				<!ELEMENT respStmt (resp, persName+)>
					<!ELEMENT resp (#PCDATA)>
					<!ELEMENT persName (#PCDATA)>
			<!ELEMENT publicationStmt (publisher, availability)>
				<!ELEMENT publisher (orgName, address?)>
					<!ELEMENT orgName (#PCDATA)>
					<!ELEMENT address (street?, postCode?, settlement?)>
						<!ELEMENT street (#PCDATA)>
						<!ELEMENT postCode (#PCDATA)>
						<!ELEMENT settlement (#PCDATA)>
				<!ELEMENT availability (licence)>
					<!ATTLIST availability status CDATA #FIXED "free">
					<!ELEMENT licence (desc+)>
						<!ATTLIST licence target CDATA #FIXED "https://creativecommons.org/licenses/by-sa/3.0/legalcode.fr">
						<!ELEMENT desc (#PCDATA)>
			<!ELEMENT sourceDesc (bibl?)>
				<!ELEMENT bibl (#PCDATA | extent)*>
					<!ELEMENT extent (#PCDATA)>
		<!ELEMENT encodingDesc (projectDesc)>
			<!ELEMENT projectDesc (#PCDATA)>
		<!ELEMENT profileDesc (langUsage, particDesc, settingDesc, textDesc)>
			<!ELEMENT langUsage (language)>
				<!ELEMENT language (#PCDATA)>
					<!ATTLIST language ident CDATA #FIXED "fr">
			<!ELEMENT particDesc (listPerson)>
				<!ELEMENT listPerson (person+)>
					<!ELEMENT person (#PCDATA)>
						<!ATTLIST person
							age CDATA #IMPLIED
							xml:id CDATA #REQUIRED
							sex (F | H) #IMPLIED>
			<!ELEMENT settingDesc (setting)>
				<!ELEMENT setting (placeName?, date, locale, activity?)>
					<!ELEMENT placeName (#PCDATA)>
						<!ATTLIST placeName type CDATA #IMPLIED>
					<!ELEMENT date (#PCDATA)>
					<!ELEMENT locale (#PCDATA)>
						<!ATTLIST locale n (CP | CE1 | CE2 | CM1 | CM2 | 6e | 5e | 4e | 3e | 2e | 1e | Tle | L1 | L2 | L3 | M1 | M2) #REQUIRED>
					<!ELEMENT activity (#PCDATA)>
			<!ELEMENT textDesc (channel, constitution, derivation, domain, factuality, interaction, preparedness, purpose+)>
				<!ATTLIST textDesc n CDATA "schoolwork">
				<!ELEMENT channel (#PCDATA)>
					<!ATTLIST channel mode CDATA #FIXED "w">
				<!ELEMENT constitution (#PCDATA)>
					<!ATTLIST constitution type CDATA #FIXED "single">
				<!ELEMENT derivation EMPTY>
					<!ATTLIST derivation type (original | revision) #REQUIRED>
				<!ELEMENT domain EMPTY>
					<!ATTLIST domain type CDATA #FIXED "education">
				<!ELEMENT factuality (#PCDATA)>
					<!ATTLIST factuality type (fact | fiction | inapplicable | mixed) #REQUIRED>
				<!ELEMENT interaction (#PCDATA)>
					<!ATTLIST interaction type CDATA #FIXED "none">
				<!ELEMENT preparedness EMPTY>
					<!ATTLIST preparedness type (formulaic | none | revised | scripted) #REQUIRED>
				<!ELEMENT purpose (#PCDATA)>
					<!ATTLIST purpose
						type (entertain | express | inform | persuade) #REQUIRED
						degree (high | low | medium | unknown) #REQUIRED>
	<!ELEMENT text (front?, body, back?)>
		<!ELEMENT front (#PCDATA | metamark | p)*>
			<!ELEMENT metamark (#PCDATA | figure | gap | hi | lb | mod | name | pb | surplus | unclear)*>
				<!ATTLIST metamark
					seq CDATA #IMPLIED
					resp (E | P | transcripteur) #REQUIRED
					rend (underline) #IMPLIED>
				<!ELEMENT lb EMPTY>
					<!ATTLIST lb rend (hyphen) #IMPLIED>
				<!ELEMENT pb EMPTY>
				<!ELEMENT gap EMPTY>
				<!ELEMENT unclear (#PCDATA | lb)*>
					<!ATTLIST unclear rend (hyphen) #IMPLIED>
				<!ELEMENT hi (#PCDATA | lb | mod | unclear)*>
					<!ATTLIST hi rend CDATA #REQUIRED>
				<!ELEMENT figure EMPTY>
				<!ELEMENT name EMPTY>
				<!ELEMENT surplus (#PCDATA)>
				<!ELEMENT mod (add | del | orig | reg | subst | mod)*>
					<!ATTLIST mod
						cat CDATA #IMPLIED
						seq CDATA #REQUIRED
						resp (E | P | chercheur) #REQUIRED
						type (add | corr | del | subst) #REQUIRED>
					<!ELEMENT add (#PCDATA | del | gap | hi | lb | mod | pb | subst | unclear)*>
					<!ELEMENT del (#PCDATA | add | gap | hi | lb | mod | pb | subst | unclear)*>
					<!ELEMENT orig (#PCDATA | add | gap | hi | lb | mod | pb | subst | unclear)*>
					<!ELEMENT reg (#PCDATA | add | gap | hi | lb | mod | pb | subst | unclear)*>
					<!ELEMENT subst (#PCDATA | add | del | gap | hi | lb | mod | pb | unclear)*>
		<!ELEMENT body (head?, p+)>
			<!ELEMENT head (#PCDATA | anchor | figure | gap | hi | lb | mod | name | pb | s | span | surplus | unclear)*>
			<!ELEMENT p (#PCDATA | anchor | figure | gap | hi | lb | mod | name | pb | s | span | surplus | unclear)*>
				<!ELEMENT span EMPTY>
					<!ATTLIST span xml:id CDATA #REQUIRED>
					<!ATTLIST span to CDATA #REQUIRED>
				<!ELEMENT anchor EMPTY>
					<!ATTLIST anchor xml:id CDATA #REQUIRED>
				<!ELEMENT s (#PCDATA)>
					<!ATTLIST s type CDATA #REQUIRED>
					<!ATTLIST s rend CDATA #REQUIRED>
					<!ATTLIST s n CDATA #REQUIRED>
		<!ELEMENT back (#PCDATA | metamark | note | p)*>
			<!ELEMENT note (#PCDATA)>
				<!ATTLIST note place CDATA #IMPLIED>
				<!ATTLIST note rend CDATA #IMPLIED>
				<!ATTLIST note resp CDATA #FIXED "P">
				<!ATTLIST note seq CDATA #REQUIRED>
				<!ATTLIST note target CDATA #REQUIRED>

=== AliSlth/CocoRebus/DATA/EC-CE1-2014-ABZ1-D1-E1-V2.xml
<?xml version='1.0' encoding='UTF8'?>
<?xml-stylesheet type="text/xsl" href="operations.xsl"?><!DOCTYPE TEI SYSTEM "../../normes.dtd">
<TEI>
 <teiHeader>
 <fileDesc>
  <titleStmt>
    <title>EC-CE1-2014-ABZ1-D1-E1-V2</title>
    <respStmt>
      <resp>récupération du fichier au format texte</resp>
      <persName>Les transcripteurs : ...</persName>
    </respStmt>
    <respStmt>
      <resp>création du header</resp>
      <persName>Serge Fleury</persName>
    </respStmt>
    <respStmt>
      <resp>pretraitement et balisage du texte selon la TEI P5</resp>
      <persName>Serge Fleury</persName>
    </respStmt>
  </titleStmt>
  <publicationStmt>
    <publisher>
      <orgName>CLESTHIA</orgName>
      <address>CLESTHIA ... ...</address>
    </publisher>
    <availability>
      <licence target="https://creativecommons.org/licenses/by-sa/3.0/legalcode.fr">
        <desc>Ce fichier numérique est mis à disposition selon les termes de la licence Creative Commons Attribution - Pas d'Utilisation Commerciale - Partage à l'Identique 3.0 France (http://creativecommons.org/licenses/by-nc-sa/3.0/fr)</desc>
        <desc>Autorisation parentale signée en 2014</desc>
      </licence>
    </availability>
  </publicationStmt>
  <sourceDesc>
    <bibl>ECRISCOL (http://www.univ-paris3.fr/ecriscol)</bibl>
  </sourceDesc>
</fileDesc>
 <encodingDesc>
  <projectDesc>
ECRISCOL
Le projet de recherche ECRISCOL est centré sur l’analyse des écrits produits en situation scolaire. Il s’agit de faire le rapport entre des traits caractéristiques de ces écrits et des situations d’apprentissage et d’enseignement suscitant leur production, de manière à faire apparaître des dispositifs didactiques favorisant certains types d'écrits et certaines stratégies ou procédures d'écriture.
objectif : cf http://www.univ-paris3.fr/ecriscol-300509.kjsp
encodage des textes selon la norme de la Text Encoding Initiative, TEIP5
http://www.tei-c.org/release/doc/tei-p5-doc
</projectDesc>
</encodingDesc>
 <profileDesc>
  <langUsage>
    <language ident="fr">french</language>
  </langUsage>
  <particDesc>
    <listPerson>
      <person xml:id="W1"/>
    </listPerson>
  </particDesc>
  <settingDesc>
    <setting>
      <placeName/>
      <date>31/03/2016</date>
      <locale xml:lang="fr" n="CE1"/>
      <locale xml:lang="en" n="2"/>
      <activity/>
    </setting>
  </settingDesc>
  <textDesc n="schoolwork">
    <channel mode="w"/>
    <constitution type="single"/>
    <derivation/>
    <domain type="education"/>
    <factuality/>
    <interaction type="none"/>
    <preparedness/>
    <purpose/>
  </textDesc>
</profileDesc>
 </teiHeader>
 <text>
<front>
</front>
<body><p>
Alors Porculus décida de <mod type="corr" cat="graph" resp="chercheur" seq="post"><orig>alé</orig><reg>aller</reg></mod><lb/>
voir dans la <mod type="corr" cat="graph" resp="chercheur" seq="post"><orig>forai</orig><reg>forêt</reg></mod> et il <mod type="corr" cat="seg" resp="chercheur" seq="post"><orig>avu</orig><reg>a vu</reg></mod><lb/>
un petit cochon il <mod type="corr" cat="graph;seg" resp="chercheur" seq="post"><orig>sapelé</orig><reg>s'appelait</reg></mod><lb/>
<mod type="del" seq="T1" resp="E"><del>loo</del></mod> locs <mod type="del" seq="T1" resp="E"><del>u</del></mod> et il <mod type="del" seq="T1" resp="E"><del>fini</del></mod><lb/>
<mod type="del" seq="T1" resp="E"><del>decis</del></mod> <mod type="corr" cat="graph" resp="chercheur" seq="post"><orig>decida</orig><reg>décida</reg></mod> de <mod type="corr" cat="graph;phon" resp="chercheur" seq="post"><orig>raité</orig><reg>rester</reg></mod><lb/>
dans la <mod type="corr" cat="graph" resp="chercheur" seq="post"><orig>foré</orig><reg>forêt</reg></mod> avec son<lb/>
<mod type="corr" cat="graph" resp="chercheur" seq="post"><orig>copin</orig><reg>copain</reg></mod><lb/>
</p>
</body>
<back/></text>
</TEI>

=== AliSlth/CocoRebus/DATA/CO-3-2014-ARG-D1-E3-V2.xml
<?xml version='1.0' encoding='UTF8'?>
<?xml-stylesheet type="text/xsl" href="operations.xsl"?><!DOCTYPE TEI SYSTEM "../../normes.dtd">
<TEI>
 <teiHeader>
 <fileDesc>
  <titleStmt>
    <title>CO-3-2014-ARG-D1-E3-V2</title>
    <respStmt>
      <resp>récupération du fichier au format texte</resp>
      <persName>Les transcripteurs : ...</persName>
    </respStmt>
    <respStmt>
      <resp>création du header</resp>
      <persName>Serge Fleury</persName>
    </respStmt>
    <respStmt>
      <resp>pretraitement et balisage du texte selon la TEI P5</resp>
      <persName>Serge Fleury</persName>
    </respStmt>
  </titleStmt>
  <publicationStmt>
    <publisher>
      <orgName>CLESTHIA</orgName>
      <address>CLESTHIA ... ...</address>
    </publisher>
    <availability>
      <licence target="https://creativecommons.org/licenses/by-sa/3.0/legalcode.fr">
        <desc>Ce fichier numérique est mis à disposition selon les termes de la licence Creative Commons Attribution - Pas d'Utilisation Commerciale - Partage à l'Identique 3.0 France (http://creativecommons.org/licenses/by-nc-sa/3.0/fr)</desc>
        <desc>Autorisation parentale signée en 2014</desc>
      </licence>
    </availability>
  </publicationStmt>
  <sourceDesc>
    <bibl>ECRISCOL (http://www.univ-paris3.fr/ecriscol)</bibl>
  </sourceDesc>
</fileDesc>
 <encodingDesc>
  <projectDesc>
ECRISCOL
Le projet de recherche ECRISCOL est centré sur l’analyse des écrits produits en situation scolaire. Il s’agit de faire le rapport entre des traits caractéristiques de ces écrits et des situations d’apprentissage et d’enseignement suscitant leur production, de manière à faire apparaître des dispositifs didactiques favorisant certains types d'écrits et certaines stratégies ou procédures d'écriture.
objectif : cf http://www.univ-paris3.fr/ecriscol-300509.kjsp
encodage des textes selon la norme de la Text Encoding Initiative, TEIP5
http://www.tei-c.org/release/doc/tei-p5-doc
</projectDesc>
</encodingDesc>
 <profileDesc>
  <langUsage>
    <language ident="fr">french</language>
  </langUsage>
  <particDesc>
    <listPerson>
      <person xml:id="W1"/>
    </listPerson>
  </particDesc>
  <settingDesc>
    <setting>
      <placeName/>
      <date>31/03/2016</date>
      <locale xml:lang="fr" n="3"/>
      <locale xml:lang="en" n="9"/>
      <activity/>
    </setting>
  </settingDesc>
  <textDesc n="schoolwork">
    <channel mode="w"/>
    <constitution type="single"/>
    <derivation/>
    <domain type="education"/>
    <factuality/>
    <interaction type="none"/>
    <preparedness/>
    <purpose/>
  </textDesc>
</profileDesc>
 </teiHeader>
 <text>
<front>
</front>
<body><p>
Je suis sorti<mod type="del" seq="T2" resp="P"><del>e</del></mod> du corps de <span xml:id="C1" to="#endC1"/>ma mère quand, j'avais <lb/>
vu, entendu,<anchor xml:id="endC1"/> plein<mod type="del" seq="T2" resp="P"><del>s</del></mod> de choses. Ma mère m'avait pri<mod type="subst" resp="E" seq="T1"><del>t</del><add>s</add></mod><lb/>
dans ses bras. J'avais ressenti de la joie, j'étais<lb/>
heureux, jusqu'<mod type="subst" resp="E" seq="T1"><del>a</del><add>à</add></mod> <mod type="del" seq="T2" resp="P"><del>c</del></mod>que ma mère perdit conscience.<lb/>
<mod type="corr" cat="graph" resp="chercheur" seq="post"><orig>j'</orig><reg>J'</reg></mod>avais <mod type="corr" cat="graph" resp="chercheur" seq="post"><orig>eus</orig><reg>eu</reg></mod> très peur. "<mod type="corr" cat="graph" resp="chercheur" seq="post"><orig>ma</orig><reg>Ma</reg></mod> mère inconsciente". Puis<lb/>
les médecins m'<mod type="corr" cat="graph" resp="chercheur" seq="post"><orig>avais</orig><reg>avaient</reg></mod> emmen<mod type="subst" resp="E" seq="T1"><del>er</del><add>é</add></mod> dans une salle. <mod type="corr" cat="graph" resp="chercheur" seq="post"><orig>j'</orig><reg>J'</reg></mod>avais très<lb/> 
peur pour ma mère, je ne s<mod type="del" seq="T2" resp="P"><del>'</del></mod>avais pas si elle allai<mod type="subst" resp="E" seq="T1"><del>s</del><add>t</add></mod><lb/>
se <mod type="corr" cat="graph" resp="chercheur" seq="post"><orig>réveillé<mod type="subst" resp="E" seq="T1"><del>e</del><add>r</add></mod></orig><reg>réveiller</reg></mod>. Soudain un médecin m'avai<mod type="subst" resp="E" seq="T1"><del>s</del><add>t</add></mod> emmen<mod type="subst" resp="E" seq="T1"><del>er</del><add>é</add></mod> auprès<lb/>
de ma mère. Je me sentais bien dans ma peau. <mod type="corr" cat="graph" resp="chercheur" seq="post"><orig>j'</orig><reg>J'</reg></mod>etais<lb/>
heureux de vivre. Sans doute c'etait un bonheur pour moi, un<lb/>
<span xml:id="C3" to="#endC3"/>bonheur égoiste<anchor xml:id="endC3"/> Un jour en me réveillant, j'avais des <lb/>
<mod type="corr" cat="graph" resp="chercheur" seq="post"><orig>douleur</orig><reg>douleurs</reg></mod>, une douleur si forte que je fermai les yeux, j'étais<lb/>
<span xml:id="C4" to="#endC4"/>incapable  de faire quoi que <mod type="corr" cat="graph" resp="chercheur" seq="post"><orig>se</orig><reg>ce</reg></mod> soit.<anchor xml:id="endC4"/> Je <mod type="corr" cat="phon" resp="chercheur" seq="post"><orig>pleur<mod type="del" seq="T2" resp="P"><del>é</del></mod></orig><reg>pleurais</reg></mod> je <mod type="corr" cat="phon" resp="chercheur" seq="post"><orig>souff<mod type="del" seq="T2" resp="P"><del>ée</del></mod></orig><reg>souffrais</reg></mod>, je<lb/> 
ne pouvais plus rien faire. Un moment la douleur fut si forte que<lb/> 
j'avais cru perdre la raison et soudain plus rien. Plus de<lb/>
douleur insu<mod type="add" seq="T2" resp="P"><add>p</add></mod>portable, rien de cela j'avais de la joie en moi.<lb/>
Puis le jour <mod type="corr" cat="graph" resp="chercheur" seq="post"><orig>ou</orig><reg>où</reg></mod> je devais <mod type="corr" cat="graph" resp="chercheur" seq="post"><orig>rentrée</orig><reg>rentrer</reg></mod> chez moi avec ma<lb/>
famille, les médecins, m'<mod type="corr" cat="graph" resp="chercheur" seq="post"><orig>avai<mod type="del" seq="T2" resp="P"><del>s</del></mod></orig><reg>avaient</reg></mod> <mod type="del" seq="T1" resp="E"><del>donne</del></mod> fait un cadeau<lb/>
merveilleux.<lb/><span xml:id="C5" to="#endC5"/> <anchor xml:id="endC5"/></p>

</body>
<back>
	<note seq="T2" resp="P" target="#C1">très mal dit</note>
	<note seq="T2" resp="P" target="#C3">B.</note>
	<note seq="T2" resp="P" target="#C4">oui</note>
	<note seq="T2" resp="P" target="#C5">
		De bonnes formulations et des <lb/> 
		passages plus passables. <lb/>
		On retrouve l'essentiel des éléments <lb/>
		attendus du texte de départ.
	</note>
</back></text>
</TEI>

=== AliSlth/CocoRebus/DATA/CO-3-2014-ARG-D1-E9-V2.xml
<?xml version='1.0' encoding='UTF8'?>
<?xml-stylesheet type="text/xsl" href="operations.xsl"?><!DOCTYPE TEI SYSTEM "../../normes.dtd">
<TEI>
 <teiHeader>
 <fileDesc>
  <titleStmt>
    <title>CO-3-2014-ARG-D1-E9-V2</title>
    <respStmt>
      <resp>récupération du fichier au format texte</resp>
      <persName>Les transcripteurs : ...</persName>
    </respStmt>
    <respStmt>
      <resp>création du header</resp>
      <persName>Serge Fleury</persName>
    </respStmt>
    <respStmt>
      <resp>pretraitement et balisage du texte selon la TEI P5</resp>
      <persName>Serge Fleury</persName>
    </respStmt>
  </titleStmt>
  <publicationStmt>
    <publisher>
      <orgName>CLESTHIA</orgName>
      <address>CLESTHIA ... ...</address>
    </publisher>
    <availability>
      <licence target="https://creativecommons.org/licenses/by-sa/3.0/legalcode.fr">
        <desc>Ce fichier numérique est mis à disposition selon les termes de la licence Creative Commons Attribution - Pas d'Utilisation Commerciale - Partage à l'Identique 3.0 France (http://creativecommons.org/licenses/by-nc-sa/3.0/fr)</desc>
        <desc>Autorisation parentale signée en 2014</desc>
      </licence>
    </availability>
  </publicationStmt>
  <sourceDesc>
    <bibl>ECRISCOL (http://www.univ-paris3.fr/ecriscol)</bibl>
  </sourceDesc>
</fileDesc>
 <encodingDesc>
  <projectDesc>
ECRISCOL
Le projet de recherche ECRISCOL est centré sur l’analyse des écrits produits en situation scolaire. Il s’agit de faire le rapport entre des traits caractéristiques de ces écrits et des situations d’apprentissage et d’enseignement suscitant leur production, de manière à faire apparaître des dispositifs didactiques favorisant certains types d'écrits et certaines stratégies ou procédures d'écriture.
objectif : cf http://www.univ-paris3.fr/ecriscol-300509.kjsp
encodage des textes selon la norme de la Text Encoding Initiative, TEIP5
http://www.tei-c.org/release/doc/tei-p5-doc
</projectDesc>
</encodingDesc>
 <profileDesc>
  <langUsage>
    <language ident="fr">french</language>
  </langUsage>
  <particDesc>
    <listPerson>
      <person xml:id="W1"/>
    </listPerson>
  </particDesc>
  <settingDesc>
    <setting>
      <placeName/>
      <date>31/03/2016</date>
      <locale xml:lang="fr" n="3"/>
      <locale xml:lang="en" n="9"/>
      <activity/>
    </setting>
  </settingDesc>
  <textDesc n="schoolwork">
    <channel mode="w"/>
    <constitution type="single"/>
    <derivation/>
    <domain type="education"/>
    <factuality/>
    <interaction type="none"/>
    <preparedness/>
    <purpose/>
  </textDesc>
</profileDesc>
 </teiHeader>
 <text>
<front>
</front>
<body><p>
<span xml:id="C1" to="#endC1"/>Quand je sors la tête puis les <mod type="corr" cat="graph" resp="chercheur"><orig>restes</orig><reg>reste</reg></mod> de mon<lb/> corps<anchor xml:id="endC1"/>, je pousse un cri<mod type="del" resp="P" seq="T2"><del>e</del></mod>. La sage<mod type="subst" seq="T2" resp="P"><del> </del><add>-</add></mod>femme me<lb/> <span xml:id="C2" to="#endC2"/><mod type="corr" cat="graph" resp="chercheur"><orig>pause</orig><reg>pose</reg></mod><anchor xml:id="endC2"/> sur le ventre de ma mère, <mod type="del" seq="T2" resp="P"><del>elle</del></mod> qui <lb/>pleure de joie. Pour la première fois j'ouvr<mod resp="E" seq="T1" type="subst"><del>ai</del><add>e</add></mod><lb/>
mes <span xml:id="C9" to="#endC9"/>yeux<anchor xml:id="endC9"/>, j'ai l'impression que mes <span xml:id="C10" to="#endC10"/>yeux<anchor xml:id="endC10"/> se <lb/>déchir<span xml:id="C3" to="#endC3"/>e<anchor xml:id="endC3"/>. Je suis à la fois content de pouvoir<lb/>
les <mod type="corr" cat="graph" resp="chercheur"><orig>ouvrir<mod resp="P" seq="T2" type="del"><del>e</del></mod></orig><reg>ouvrir</reg></mod> et à la fois non car <mod type="corr" cat="seg" resp="chercheur"><orig>ilya</orig><reg>il y a</reg></mod> une <lb/> <mod type="corr" cat="phon" resp="chercheur"><orig>lumiere</orig><reg>lumière</reg></mod> intense <mod type="corr" cat="seg" resp="chercheur"><orig>etun</orig><reg>et un</reg></mod> petit air<mod type="del" seq="T2" resp="P"><del>e</del></mod> frais. La <mod type="corr" cat="seg" resp="chercheur"><orig>sage<lb/>
femme</orig><reg>sage-femme</reg></mod> me coupe le cordon <mod type="subst" resp="P" seq="T2"><del>obilical</del><add>ombilical</add></mod> et me<lb/>
couvre avec une couverture. Il y <span xml:id="C4" to="#endC4"/>avai<mod type="subst" resp="P" seq="T2"><del>s</del><add>t</add></mod><anchor xml:id="endC4"/> mon<lb/>
<mod type="del" seq="T1" resp="E"><del>pel</del></mod> père qui me <mod type="corr" cat="phon" resp="chercheur"><orig>regar<span xml:id="C5" to="#endC5"/>de<anchor xml:id="endC5"/></orig><reg>regardait</reg></mod> avec <span xml:id="C6" to="#endC6"/>des yeux<anchor xml:id="endC6"/> qui<lb/>
peti<span xml:id="C7" to="#endC7"/>lle<anchor xml:id="endC7"/> qui expri<span xml:id="C8" to="#endC8"/>me<anchor xml:id="endC8"/> de la joie et beaucoup<lb/>
<mod type="corr" cat="seg" resp="chercheur"><orig>démotion</orig><reg>d'émotion</reg></mod><lb/>
</p>
</body>
<back>
	<note seq="T2" resp="P" rend="underline" target="#C1">Très mal exprimé</note>
	<note seq="T2" resp="P" rend="underline" target="#C2">"poser"</note>
	<note seq="T2" resp="P" rend="underline" target="#C3">Problème: <lb/>sujet au singulier<lb/> et verbe au pluriel</note>
	<note seq="T2" resp="P" rend="underline" target="#C4">attention à <mod resp="P" seq="T2" type="del"><del>garder</del></mod><lb/>la concordance des temps</note>
	<note seq="T2" resp="P" rend="underline" target="#C5">attention à <lb/>la concordance des temps</note>
	<note seq="T2" resp="P" rend="underline" target="#C6">problème <lb/>d'accord</note>
	<note seq="T2" resp="P" rend="underline" target="#C7"> </note>
	<note seq="T2" resp="P" rend="underline" target="#C8"> </note>
	<note seq="T2" resp="P" rend="underline" target="#C9"/>
	<note seq="T2" resp="P" rend="underline" target="#C10"/>
	<metamark seq="T2" resp="P">On ne retrouve pas tous les éléments <lb/>attendus à la fin du texte de base.</metamark>
</back>
</text>
</TEI>
